spring:
  datasource:
    url: ""
    driver-class-name: ""
    username: ""
    password: ""
  sql:
    init:
      mode: never

password:
  bcrypt:
    regex: ^\$(2[abyx])\$.*$
  numeric:
    regex: \d{6}
