spring:
  datasource:
    url: jdbc:mysql://localhost:3307/stock?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bj0451heb
    hikari:
     pool-name: stock-hikari
  jpa:
    hibernate:
      ddl-auto: create  
    show-sql: true  
    properties:
      hibernate:
        '[format_sql]': true  
        '[use_sql_comments]': true 
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ""  # 如果 Redis 无密码，则留空
      database: 0   # 默认使用 0 号数据库
      timeout: 5s   # 连接超时时间（支持 s/ms）
      client-type: lettuce  # 显式指定 Lettuce 作为 Redis 客户端
      lettuce:
        pool:
          enabled: true  # 启用连接池
          max-active: 8  # 连接池最大连接数
          max-idle: 8    # 最大空闲连接数
          min-idle: 0    # 最小空闲连接数
          max-wait: 1s   # 连接等待时间（支持 s/ms）
      repositories:
        enabled: false
  sql:
    init:
      mode: never

snowflake:
  workerId: 1 # 

jwt:
  secret: 
  ttl: 36000000 # 10h

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: default_producer_group
    send-message-timeout: 3000
  consumer:
    group: default_consumer_group
    topic: DEFAULT_TOPIC

rocketmq-config:
  producers:
    trade: trade_producer_group
    capital: capital_producer_group
    position: position_producer_group
    securities: securities_producer_group
  
  consumers:
    trade: trade_consumer_group
    capital: capital_consumer_group
    position: position_consumer_group
    securities: securities_consumer_group

  topics:
    trade: TRADE_TOPIC
    match: MATCH_TOPIC
    position: POSITION_TOPIC
    capital: CAPITAL_TOPIC
    securities: SECURITIES_TOPIC

  tags:
    trade-create: TRADE_CREATE
    trade-confirm: TRADE_CONFIRM
    trade-cancel: TRADE_CANCEL
<<<<<<< HEAD
    trade-validity-check: TRADE_VALIDITY_CHECK
=======
>>>>>>> 13c6d9d36c826dd91c3f04d952de90f7b349efbe
    capital-check: CAPITAL_CHECK
    capital-validity-check: CAPITAL_VALIDITY_CHECK
    capital-validity-confirm: CAPITAL_VALIDITY_CONFIRM
    securities-check: SECURITIES_CHECK
